# Generated by Django 6.0.7 on 2026-08-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('filter_rules', models.JSONField(default=dict, verbose_name='Reglas de filtro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa o emprendimiento')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Cargo')),
                ('industry', models.CharField(blank=True, max_length=150, verbose_name='Rubro')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Región')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Comuna')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='Fuente u origen')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('unconfirmed', 'Sin confirmar'), ('unsubscribed', 'Dado de baja'), ('bounced', 'Correo rebotado'), ('blocked', 'Bloqueado'), ('spam', 'Marcado como spam')], default='active', max_length=20, verbose_name='Estado')),
                ('consent_status', models.BooleanField(default=True, verbose_name='Estado de consentimiento')),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de consentimiento')),
                ('consent_source', models.CharField(blank=True, max_length=200, verbose_name='Origen de consentimiento')),
                ('last_interaction', models.DateTimeField(blank=True, null=True, verbose_name='Última interacción')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observaciones internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='contacts.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
