# Generated by Django 6.0.7 on 2026-08-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Último Acceso'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña al iniciar sesión'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('humm_admin', 'Administrador Humm'), ('org_admin', 'Administrador de Organización'), ('campaign_editor', 'Editor de Campañas'), ('viewer', 'Visualizador / Analista')], default='viewer', max_length=20, verbose_name='Rol en la plataforma'),
        ),
    ]
