# Generated by Django 6.0.7 on 2026-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_login_ip_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('company_name', models.CharField(max_length=150, verbose_name='Emprendimiento o Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono o WhatsApp')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje o Consulta Opcional')),
                ('privacy_accepted', models.BooleanField(default=True, verbose_name='Aceptó Política de Privacidad')),
                ('source', models.CharField(default='landing_hummailing', max_length=100, verbose_name='Origen del Lead')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM Content')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Contacto'), ('contacted', 'Contactado'), ('converted', 'Convertido a Cliente'), ('discarded', 'Descartado')], default='pending', max_length=30, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas Humm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Captación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Prospecto / Lead',
                'verbose_name_plural': 'Prospectos / Leads (Landing)',
                'ordering': ['-created_at'],
            },
        ),
    ]
