# Generated by Django 6.0.7 on 2026-08-28 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('rut', models.CharField(blank=True, max_length=50, verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Principal')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Sitio Web')),
                ('logo', models.CharField(blank=True, max_length=500, verbose_name='URL del Logo del Cliente')),
                ('default_sender_name', models.CharField(default='Hummailing', max_length=150, verbose_name='Nombre del Remitente')),
                ('default_sender_email', models.EmailField(default='hola@humm.cl', max_length=254, verbose_name='Correo de Envío Autorizado')),
                ('default_reply_to', models.EmailField(blank=True, default='hola@humm.cl', max_length=254, verbose_name='Correo de Respuesta (Reply-To)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección Comercial')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('closed', 'Cerrada')], default='active', max_length=20, verbose_name='Estado')),
                ('max_contacts', models.PositiveIntegerField(default=1000, verbose_name='Límite Máximo de Contactos')),
                ('monthly_email_limit', models.PositiveIntegerField(default=5000, verbose_name='Límite Mensual de Envíos')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Responsable en Humm')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='Acción Realizada')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Excluido')),
                ('reason', models.CharField(choices=[('unsub', 'Cancelación de Suscripción'), ('bounce_perm', 'Rebote Permanente (Hard Bounce)'), ('spam', 'Queja por Spam')], default='unsub', max_length=30, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Entrada de Exclusión',
                'verbose_name_plural': 'Lista de Exclusiones',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
