# Generated by Django 6.0.7 on 2026-08-28 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título Interno del Comunicado')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto del Correo')),
                ('message', models.TextField(verbose_name='Contenido del Mensaje')),
                ('target_audience', models.CharField(choices=[('all_active_orgs', 'Todos los Administradores de Empresas Activas'), ('all_users', 'Todos los Usuarios Registrados')], default='all_active_orgs', max_length=50, verbose_name='Destinatarios')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Destinatarios')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Envío')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado Por')),
            ],
            options={
                'verbose_name': 'Comunicado Masivo a Clientes',
                'verbose_name_plural': 'Comunicados Masivos a Clientes',
                'ordering': ['-sent_at'],
            },
        ),
    ]
