# Generated by Django 6.0.7 on 2026-08-28 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0005_alter_campaign_options_and_more'),
        ('contacts', '0002_alter_segment_options_alter_tag_options_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título / Oportunidad')),
                ('interest_topic', models.CharField(blank=True, max_length=200, verbose_name='Tema o Servicio de Interés')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('to_contact', 'Por contactar'), ('contacted', 'Contactado'), ('in_conversation', 'En conversación'), ('proposal_sent', 'Propuesta enviada'), ('won', 'Ganada / Venta cerrada'), ('not_interested', 'No interesado'), ('lost', 'Perdida')], default='new', max_length=30, verbose_name='Estado Comercial')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta / Urgente')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de Seguimiento')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='Próxima Acción')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo Responsable')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='campaigns.campaign', verbose_name='Campaña de Origen')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='contacts.contact', verbose_name='Contacto Prospecto')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='campaigns.campaignlink', verbose_name='Enlace de Conversión')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Oportunidad Comercial',
                'verbose_name_plural': 'Oportunidades Comerciales',
                'ordering': ['-created_at'],
            },
        ),
    ]
