# Generated by Django 6.0.7 on 2026-08-01 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(blank=True)),
                ('html_content', models.TextField(verbose_name='Contenido HTML base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre interno')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto')),
                ('preheader', models.CharField(blank=True, max_length=250, verbose_name='Texto de preencabezado')),
                ('sender_name', models.CharField(default='Humm', max_length=150)),
                ('sender_email', models.EmailField(default='hola@humm.cl', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('content_blocks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En revisión'), ('scheduled', 'Programada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='contacts.segment')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaigntemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('link_type', models.CharField(choices=[('info', 'Informativo'), ('conversion', 'Conversión'), ('unsubscribe', 'Desuscripción')], default='info', max_length=20)),
                ('service_interest', models.CharField(blank=True, help_text='Si es conversión, qué servicio es', max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Envío'), ('delivered', 'Entrega'), ('bounce_temp', 'Rebote temporal'), ('bounce_perm', 'Rebote permanente'), ('open', 'Apertura'), ('click', 'Clic'), ('reply', 'Respuesta'), ('unsub', 'Cancelación de suscripción'), ('spam', 'Queja por spam'), ('error', 'Error')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contacts.contact')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaignlink')),
            ],
        ),
    ]
