# Generated by Django 6.0.7 on 2026-08-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_tag',
            field=models.ForeignKey(blank=True, help_text='Enviar a una etiqueta específica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.tag'),
        ),
    ]
