# Generated by Django 6.0.7 on 2026-08-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_target_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo comenzó el envío', null=True),
        ),
    ]
