# Generated by Django 6.0.7 on 2026-08-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, default='rmerino@humm.cl', max_length=254),
        ),
    ]
