# Generated by Django 6.0.7 on 2026-08-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_reply_to'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='campaigntemplate',
            options={'verbose_name': 'Plantilla de Campaña', 'verbose_name_plural': 'Plantillas de Campaña'},
        ),
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Evento de Seguimiento', 'verbose_name_plural': 'Eventos de Seguimiento'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='campaignlink',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list, verbose_name='Bloques de la plantilla'),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization', verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, default='hola@humm.cl', max_length=254),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sender_name',
            field=models.CharField(default='Hummailing', max_length=150),
        ),
        migrations.AlterField(
            model_name='campaignlink',
            name='service_interest',
            field=models.CharField(blank=True, help_text='Si es conversión, qué servicio o tema es', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='html_content',
            field=models.TextField(blank=True, verbose_name='Contenido HTML base'),
        ),
    ]
