# Generated by Django 6.0.7 on 2026-08-30 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora programada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='campaigns.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Programación de Campaña',
                'verbose_name_plural': 'Programaciones de Campaña',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
